# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: dpentlan <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/11/07 14:36:56 by dpentlan          #+#    #+#              #
#    Updated: 2022/11/07 14:36:58 by dpentlan         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = libft

SRC = isalpha.c\
	# isdigit.c\
	# isalnum.c\
	# isascii.c\
	# isprint.c\
	# strlen.c\
	# memset.c\
	# bzero.c\
	# memcpy.c\
	# memmove.c\
	# strlcpy.c\
	# strlcat.c\
	# toupper.c\
	# tolower.c\
	# strchr.c\
	# strrchr.c\
	# strncmp.c\
	# memchr.c\
	# strnstr.c\
	# atoi.c\
	# calloc.c\		# Can use malloc()
# strdup.c		# Can use malloc()

all: $(NAME)

clean:

fclean:

re:


# example from rush 02

# NAME = rush-0

# SRC = arithmetic_1000_split_int.c\
# 	main.c\
# 	ft_strlen.c\
# 	ft_putstr.c\
# 	dict_build.c\
# 	dict_clean.c\
# 	print_num_1.c\
# 	print_num_2.c\
# 	dict_parse.c

# SRC_FOLDER = srcs/

# HEADERS_FOLDER = includes/

# OBJS = $(patsubst %.c,$(OBJ_FOLDER)%.o,$(SRC))

# OBJ_FOLDER = $(SRC_FOLDER)

# CFLAGS = -Wall -Wextra -Werror -ggdb

# all: $(NAME)
	
# $(NAME): $(OBJS)
# 	 gcc $(CFLAGS) -I$(HEADERS_FOLDER) $(OBJS) -o $(NAME)

# $(OBJ_FOLDER)%.o : $(SRC_FOLDER)%.c
# 	gcc -c $(CFLAGS) -I$(HEADERS_FOLDER) $< -o $@

# clean:
# ifneq ($(strip $(foreach f,$(OBJS),$(wildcard $(f)))),)
# 	rm -f $(strip $(foreach f,$(OBJS),$(wildcard $(f))))
# endif

# fclean: clean
# ifneq ($(wildcard($(NAME))),)
# 	rm $(NAME)
# endif

# re: fclean all